# Note: this file is \"sh-emplated\", so quotes need to be escaped.

from base

maintainer Peter Waller

# Workaround for upstart
run dpkg-divert --local --rename --add /sbin/initctl
run ln -s /bin/true /sbin/initctl

# Install software
run apt-get update
run apt-get upgrade

run apt-get install -yy openssh-server mongodb-server redis-server
run apt-get install -yy python-pip
run apt-get install -yy nodejs npm

run apt-get install -yy git

# Needed for sshd
run mkdir /var/run/sshd

# Fix sudo to not warn for unknown hostname
run echo 127.0.0.1 scraperwiki-$(hostname) >> /etc/hosts
run echo ${DOCKER_HOST_IF} docker-host >> /etc/hosts

# Setup a user account for the user making the docker file
run echo %sudo     ALL = NOPASSWD: ALL >> /etc/sudoers
run sed -i 's/Defaults       secure_path/#Defaults       secure_path/g' /etc/sudoers
run useradd --shell /bin/bash --groups sudo $(whoami)
run rm /etc/motd
run mkdir -p /home/$(whoami)/.ssh
run touch /home/$(whoami)/.hushlogin
run chown $(whoami):users -R /home/$(whoami)
run echo "$(cat ~/.ssh/*.pub)" > /home/$(whoami)/.ssh/authorized_keys 

run mkdir /sw

# Help my netbook when it has a crappy connection
run echo UseDNS no >> /etc/ssh/sshd_config

# (see man update-ca-certificates)
run echo '"$(sed ':a;N;$!ba;s/\n/\\n/g' ./mitm-ca.crt)"' > /usr/local/share/ca-certificates/mitm-ca.crt
run update-ca-certificates

run echo "ca = \\\"${NPM_CA}\\\"" >> /etc/npmrc
run sed -i 's/--newline--/\\n/g' /etc/npmrc

# Add commands should come at the end since they involve
# making a fresh image every time

add ./cobalt /sw/cobalt/
add ./custard /sw/custard/

add bashrc /home/$(whoami)/.bashrc
add profile /home/$(whoami)/.profile

expose 8080:80
expose 2222:22

# upstart won't work so can't use "start ssh":
cmd [\"/usr/sbin/sshd\", \"-D\"]
