#! /bin/bash
# above shebang is for syntax highlighting only. This file is shemplated.

from sw-base

# Let's put some installation up top.
# TODO(pwaller): uncomment this
# run apt-get install -yy python-cairo python-poppler ipython

# Fix sudo to not warn for unknown hostname
run echo 127.0.0.1 scraperwiki-$(hostname) >> /etc/hosts
run echo ${DOCKER_HOST_IF} docker-host >> /etc/hosts

# Setup a user account for the user making the docker file
run useradd --uid "${EUID}" --shell /bin/bash --groups sudo $(whoami)
run rm /etc/motd
run mkdir -p /home/$(whoami)/.ssh
run touch /home/$(whoami)/.hushlogin
run chown $(whoami):users -R /home/$(whoami)
run echo "$(cat ~/.ssh/*.pub)" > /home/$(whoami)/.ssh/authorized_keys 

# (see man update-ca-certificates)
run echo '"$(sed ':a;N;$!ba;s/\n/\\n/g' local/mitm-ca.crt)"' > /usr/local/share/ca-certificates/mitm-ca.crt
run update-ca-certificates

run mkdir -p /sw/node/etc/
run echo "ca = \\\"${NPM_CA}\\\"" >> /sw/node/etc/npmrc
run sed -i 's/--newline--/\\n/g' /sw/node/etc/npmrc

# Add commands should come at the end since they involve
# making a fresh image every time
add ./sw /sw/

add ./local/bashrc /home/$(whoami)/.bashrc
add ./local/profile /home/$(whoami)/.profile

expose 8080:80
expose 2222:22

# upstart won't work so can't use "start ssh":
cmd [\"/usr/sbin/sshd\", \"-D\"]