#! /bin/bash
# above shebang is for syntax highlighting only. This file is shemplated.
# Note: this file is \"sh-emplated\", so quotes need to be escaped.

from base

maintainer Peter Waller

# Workaround for upstart
run dpkg-divert --local --rename --add /sbin/initctl
run ln -s /bin/true /sbin/initctl

# Install software
run apt-get update
run apt-get upgrade

run apt-get install -yy openssh-server mongodb-server redis-server
run apt-get install -yy python-pip
run apt-get install -yy vim
# Note: we install node to /sw without a package manager.
# run apt-get install -yy nodejs npm

run apt-get install -yy git

# Install revent version of node
run wget http://nodejs.org/dist/v0.10.17/node-v0.10.17-linux-x64.tar.gz --output-document=/root/node.tar.gz
run mkdir -p /sw/node
run tar vxf /root/node.tar.gz --strip-components=1 --directory=/sw/node
run echo export PATH=\\\"/sw/node/bin:\\\$PATH\\\" >> /etc/profile

# Needed for sshd
run mkdir /var/run/sshd

# Help my netbook when it has a crappy connection by not waiting on DNS
run echo UseDNS no >> /etc/ssh/sshd_config

# Allow sudo group to sudo without a password
run echo %sudo     ALL = NOPASSWD: ALL >> /etc/sudoers

# Don't use secure_path
run sed -i 's/Defaults\tsecure_path/#Defaults\tsecure_path/g' /etc/sudoers
